// <auto-generated />
namespace Books.Web.DataContexts.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DefaultShema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DefaultShema));
        
        string IMigrationMetadata.Id
        {
            get { return "201611122153085_DefaultShema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
